In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.pipeline import make_pipeline
from ipywidgets import interact
from ipywidgets import IntSlider

%config InlineBackend.figure_format = 'retina'

In [2]:
data_full = pd.read_csv('/Users/konansul/Downloads/Advertising.csv', index_col = 0)

In [3]:
data_full

TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [4]:
data = data_full.drop('Newspaper', axis = 1)

In [5]:
data

TV  Radio  Sales
1    230.1   37.8   22.1
2     44.5   39.3   10.4
3     17.2   45.9    9.3
4    151.5   41.3   18.5
5    180.8   10.8   12.9
..     ...    ...    ...
196   38.2    3.7    7.6
197   94.2    4.9    9.7
198  177.0    9.3   12.8
199  283.6   42.0   25.5
200  232.1    8.6   13.4

[200 rows x 3 columns]

In [6]:
X = data[['TV', 'Radio']]

In [7]:
y = data['Sales']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [9]:
polynomial = PolynomialFeatures(degree = 3)

In [10]:
x_train_polynomial = polynomial.fit_transform(np.array(X_train))

In [11]:
x_train_polynomial

array([[1.00000000e+00, 1.16000000e+02, 7.70000000e+00, ...,
        1.03611200e+05, 6.87764000e+03, 4.56533000e+02],
       [1.00000000e+00, 1.77000000e+02, 9.30000000e+00, ...,
        2.91359700e+05, 1.53087300e+04, 8.04357000e+02],
       [1.00000000e+00, 4.31000000e+01, 2.67000000e+01, ...,
        4.95981870e+04, 3.07255590e+04, 1.90341630e+04],
       ...,
       [1.00000000e+00, 2.17700000e+02, 3.35000000e+01, ...,
        1.58767521e+06, 2.44313825e+05, 3.75953750e+04],
       [1.00000000e+00, 1.65600000e+02, 1.00000000e+01, ...,
        2.74233600e+05, 1.65600000e+04, 1.00000000e+03],
       [1.00000000e+00, 2.80200000e+02, 1.01000000e+01, ...,
        7.92971604e+05, 2.85832020e+04, 1.03030100e+03]])

In [12]:
model = LinearRegression()

In [13]:
model.fit(x_train_polynomial, y_train)

LinearRegression()

In [14]:
model.coef_, model.intercept_

(array([ 0.00000000e+00,  8.57911517e-02,  4.25967902e-02, -4.12228920e-04,
         1.18065128e-03, -4.76647648e-04,  7.11082546e-07, -5.96205229e-07,
         6.16207461e-07,  6.54894889e-06]),
 np.float64(4.217506259895185))

In [15]:
x_test_polynomial = polynomial.transform(np.array(X_test))

In [16]:
y_pred = model.predict(x_test_polynomial)

In [17]:
y_pred

array([17.09820401, 22.39742366, 21.30426012,  6.93435417, 24.07977302,
       12.86675681, 22.45693354,  8.67721778, 11.66366669, 15.50461235,
        8.3021258 ,  8.46031859, 11.80763082,  5.88452838, 10.50297127,
       12.12900643,  6.03284914, 16.33644972, 11.12211297, 18.70721171,
       19.77433654, 12.48786129, 10.10387985, 21.90997812,  9.50316642,
        7.94270695, 22.0483836 , 12.86364827, 10.65132257,  6.11970543,
       11.23391507, 10.77947956, 23.03359384,  7.93522755, 16.05020802,
       20.69706556, 11.78929506, 20.57734016, 12.22792039,  6.3980352 ])

In [18]:
(y_pred - y_test)[:10]

96     0.198204
16    -0.002576
31    -0.095740
159   -0.365646
129   -0.620227
116    0.266757
70     0.156934
171    0.277218
175    0.163667
46     0.604612
Name: Sales, dtype: float64

In [19]:
MAPE = mean_absolute_percentage_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
RMSE = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"Mean Absolute Persentage Error: {MAPE:.5f}%")
print(f"Mean Absolute Error: {MAE:.5f}")
print(f"Root Mean Squared Error: {RMSE:.5f}")

Mean Absolute Persentage Error: 0.03234%
Mean Absolute Error: 0.33585
Root Mean Squared Error: 0.42274


In [20]:
degrees = range(1, 15)

print(f"{'Degree':>6}   {'MAE':>10}   {'MAPE (%)':>10}   {'RMSE':>10}")

for degree in degrees:
    polynomial_2 = make_pipeline(PolynomialFeatures(degree))
    x_train_poly = polynomial_2.fit_transform(np.array(X_train))
    model_2 = LinearRegression()
    model_2.fit(x_train_poly, y_train)
    x_test_polynomial = polynomial_2.transform(np.array(X_test))
    y_pred = model_2.predict(x_test_polynomial)

    mae = mean_absolute_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    print(f"{degree:6}   {mae:10.4f}   {mape:10.2f}   {rmse:10.4f}")

Degree          MAE     MAPE (%)         RMSE
     1       1.4443         0.15       1.7714
     2       0.4935         0.05       0.6035
     3       0.3359         0.03       0.4227
     4       0.3570         0.03       0.4381
     5       0.3978         0.04       0.4952
     6       0.4333         0.04       0.5278
     7       0.4378         0.04       0.5089
     8       0.6315         0.06       0.8222
     9       0.7237         0.08       1.0579
    10       0.7859         0.08       1.0689
    11       1.1595         0.12       1.5792
    12       1.2510         0.14       1.7113
    13       1.4518         0.15       1.8465
    14       1.5734         0.17       1.9882


In [21]:
def static_surface(X_train, y_train, degree):
    x0 = np.array(X_train['TV'])
    x1 = np.array(X_train['Radio'])
    y = np.array(y_train)
    X = np.c_[x0, x1]

    x0_range = np.linspace(x0.min(), x0.max(), 30)
    x1_range = np.linspace(x1.min(), x1.max(), 30)
    x0_grid, x1_grid = np.meshgrid(x0_range, x1_range)
    X_grid = np.c_[x0_grid.ravel(), x1_grid.ravel()]

    model = make_pipeline(PolynomialFeatures(degree), LinearRegression())
    model.fit(X, y)
    y_pred = model.predict(X_grid).reshape(x0_grid.shape)

    fig = go.Figure()
    
    fig.add_trace(go.Scatter3d(
    x = x0, y = x1, z = y, mode = 'markers', marker = dict(size = 4, color = 'red'), name = 'Data Points'
    ))
    
    fig.add_trace(go.Surface(
    x = x0_grid, y = x1_grid, z = y_pred, opacity = 0.6, colorscale = 'Viridis', name = 'Polynomial Surface'
    ))
    
    fig.update_layout(
    scene = dict(
        xaxis_title = 'TV', yaxis_title = 'Radio', zaxis_title = 'Sales'
    ),
    title = 'Polynomial regression surface',
    width = 1000,
    height = 700
    )
    
    fig.show()


In [22]:
static_surface(X_train, y_train, 3)

In [23]:
x0 = np.array(X_train['TV'])
x1 = np.array(X_train['Radio'])
y = np.array(y_train)
X = np.c_[x0, x1]

x0_range = np.linspace(x0.min(), x0.max(), 30)
x1_range = np.linspace(x1.min(), x1.max(), 30)
x0_grid, x1_grid = np.meshgrid(x0_range, x1_range)
X_grid = np.c_[x0_grid.ravel(), x1_grid.ravel()]

def dynamic_surface(degree=2):
    model = make_pipeline(PolynomialFeatures(degree), LinearRegression())
    model.fit(X, y)
    
    y_pred = model.predict(X_grid)
    y_pred_grid = y_pred.reshape(x0_grid.shape)
    
    fig = go.Figure()
    
    fig.add_trace(go.Scatter3d(
    x = x0, y = x1, z = y, mode = 'markers', marker = dict(size = 4, color = 'red'), name = 'Data Points'
    ))

    fig.add_trace(go.Surface(
    x = x0_grid, y = x1_grid, z = y_pred_grid, opacity = 0.6, colorscale = 'Viridis', name = 'Polynomial Surface'
    ))

    fig.update_layout(
    scene = dict(
        xaxis_title = 'TV', yaxis_title = 'Radio', zaxis_title = 'Sales'
    ),
    title = 'Polynomial regression surface',
    width = 1000,
    height = 700
    )
    
    fig.show()

interact(dynamic_surface, degree = IntSlider(min = 1, max = 30, step = 1, value = 2))

interactive(children=(IntSlider(value=2, description='degree', max=30, min=1), Output()), _dom_classes=('widge…

<function __main__.dynamic_surface(degree=2)>

In [24]:
X_final = data_full[['TV', 'Radio', 'Newspaper']]
Y_final = data_full['Sales']

In [25]:
polynomial_final = PolynomialFeatures(degree = 3)

In [26]:
X_poly_final = polynomial_final.fit_transform(X_final)

In [27]:
X_poly_final.shape

(200, 20)

In [28]:
model_final = LinearRegression()

In [29]:
model_final.fit(X_poly_final, Y_final)

LinearRegression()

In [30]:
model_final.coef_, model_final.intercept_

(array([ 0.00000000e+00,  8.96744296e-02,  3.87306507e-02,  1.40116785e-02,
        -4.39852532e-04,  1.38525353e-03, -2.11551525e-04, -5.78622015e-04,
        -3.39038010e-04,  2.30693237e-04,  7.62775843e-07, -1.21636828e-06,
         7.24494002e-07,  1.79932497e-06, -1.51021227e-06, -1.14841391e-07,
         3.32749144e-06,  4.93904244e-06,  2.67349509e-06, -2.30514930e-06]),
 np.float64(3.9435738173464454))